### ISSUE TITLE
Master Issue: Initial GUI (in WPiOS)

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#13]
This is the master thread for all things GUI in WPiOS.

- [x] Basic GUI.
 - [x] Show an editable title field.
 - [x] Show an editable content view.
- [x] Toolbar.
 - [x] Make the toolbar come up on top of the keyboard when editing.
 - [x] Enable the bold button.
 - [x] Enable the italic button.
 - [x] Enable the underline button.
 - [x] Enable the strikethrough button.
 - [x] Enable the blockquote button.
 - [x] Enable the ordered list button.
 - [x] Enable the unordered list button.
 - [x] Enable the link button.
 - [x] Enable the media button.

**Comment by diegoreymendez** [comment]
I'm removing all media steps from this issue as there's now a [specifi issue](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/22) for that.  Media is still not a priority.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Not everything here is doable yet, since most of the logic is not implemented in the library.

Feel free to just reproduce what we have in the demo app.
