### ISSUE TITLE
Master Issue: Media (in Demo App).

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#21]
Add media support in the demo app.  It doesn't really need to access any services at all.  It only needs to emulate uploading and all media interactions just like the old editor did (we can use it for reference).

Tasks:
- [x] Media picker
- [x] Show media inline
- [x] Resize Media to fit screen
- [ ] Upload pictures
- [ ] Upload videos
- [ ] Cancel uploads in progress
- [x] Edit meta-data
- [x] Load media from HTML
- [x] Save media to HTML

**Comment by diegoreymendez** [comment]
@jleandroperez - Just added image loading from HTML.

**Comment by jleandroperez** [comment]
@diegoreymendez Image Loading looks amazing, congratz there!!!

**Comment by diegoreymendez** [comment]
@SergioEstevao implemented saving-media-to-html in [this PR](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/84) so I marked it here as complete.

**Comment by diegoreymendez** [comment]
I'm closing this.  I'll add a separate ticket for the fake uploads interface in the example app.
