### ISSUE TITLE
Master Issue: Export Component.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#3]
Master issue for the HTML export component.

- [x] Parse from NSAttributedString to an internal representation of HTML.
 - [x] Write basic implementation.
 - [x] Handle HTML attributes.
 - [x] Complete unit tests coverage.
- [x] Parse from the internal representation of HTML to HTML.
 - [x] Write basic implementation.
 - [x] Handle HTML attributes.
 - [x] Complete unit tests coverage.

**Comment by diegoreymendez** [comment]
@bummytime - This is the master thread for the export component.  I'll be joining you here as soon as the import component is complete.  Feel free to update in the meanwhile, or spawn child issues if necessary.

**Comment by bummytime** [comment]
@diegoreymendez roger that!

**Comment by diegoreymendez** [comment]
@bummytime - Updated the checklist today.  Let me know if there's anything else to add / change.

**Comment by diegoreymendez** [comment]
I'm closing this guy up as the unit-test coverage is good enough for now.
