### ISSUE TITLE
Master Issue: Initial GUI (in Demo App)

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#4]
This is the master thread for all things GUI in the Demo App.
- [x] Basic GUI.
  - [x] Show an editable title field.
  - [x] Show an editable content view.
- [ ] Toolbar.
  - [x] Make the toolbar come up on top of the keyboard when editing.
  - [x] Enable the bold button.
  - [x] Enable the italic button.
  - [x] Enable the underline button.
  - [x] Enable the strikethrough button.
  - [x] Enable the blockquote button.
  - [ ] Enable the ordered list button.
  - [ ] Enable the unordered list button.
  - [ ] Enable the link button.
  - [ ] Enable the media button.

**Comment by diegoreymendez** [comment]
@aerych - Feel free to create child issues for anything you tackle from this list.

**Comment by diegoreymendez** [comment]
Re-scheduling for sprint #3 since a lot of detail items were added to this issue.  In hindsight, this was a bit much to handle for sprint #2 alone.

**Comment by diegoreymendez** [comment]
I'm removing myself from this issue for now since all of the work was done by @aerych.

**Comment by diegoreymendez** [comment]
I'm removing all media steps from this issue as there [a new issue](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/21) for them.  The reason is media is not a priority yet, and would interfere with this issue's planning.

**Comment by diegoreymendez** [comment]
Since this is dependant on other features, I'm marking it for a future sprint.

**Comment by diegoreymendez** [comment]
I'm wrapping this issue up now, since it's too generic to be of use.
