### ISSUE TITLE
Blockquote support.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Aztec-iOS#76]
Add blockquote support to the editor.

Task list:
- [x] #143 Improve caret calculation
- [x] #144 Caret disappears on new line
- [x] #145 Custom attributes removed on new line
- [ ] DOM implementation

**Comment by diegoreymendez** [comment]
@koke - Will work on initial support for this feature in Iteration 7.  We do expect this feature could require additional time.
